### ISSUE TITLE
warehouse/

### ISSUE THREAD

**Issue by d-theus** [mirea-fcyb-2015/reqmanage#10]
Что это за папка?
Если нужна, то зачем - в ответном комменте.
Если нет, то в .gitignore + коммит.
Если случайно попала, то удалить + коммит.

В остальном претензий нет.

**Comment by Revenkroz** [comment]
Да она особо не нужна. В ней хранятся прикрепленные к требованиям файлы.

**Comment by d-theus** [comment]
Так их не нужно хранить в готовом приложении? Они для отладки / разработки, как тестовые данные?

**Comment by Revenkroz** [comment]
Да, не нужно. Удалю в ближайшем коммите.

**Comment by Revenkroz** [comment]
Папка удалена в коммите 0661a992dc7b0c6e0ea18c2300034a94163e0855
